"""empty message

Revision ID: 0001_initial
Revises: 
Create Date: 2024-12-09 20:51:40.074241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False, comment='Название проекта'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание проекта'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='Дата начала'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Дата окончания'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Название роли'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('taskstatus',
    sa.Column('name', sa.String(), nullable=False, comment='Название статуса задачи'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('email', sa.String(), nullable=True, comment='Электронная почта'),
    sa.Column('phone', sa.String(), nullable=True, comment='Телефон'),
    sa.Column('password_hash', sa.String(), nullable=False, comment='Хэш пароля'),
    sa.Column('role', sa.Integer(), nullable=False, comment='Идентификатор роли'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activitylog',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('action', sa.String(), nullable=False, comment='Действие'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Временная метка'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Идентификатор проекта'),
    sa.Column('title', sa.String(), nullable=False, comment='Название задачи'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание задачи'),
    sa.Column('status', sa.UUID(), nullable=False, comment='Идентификатор статуса задачи'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Срок выполнения'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='Создано пользователем'),
    sa.Column('assigned_to', sa.UUID(), nullable=False, comment='Назначено пользователю'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['status'], ['taskstatus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Идентификатор задачи'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('content', sa.String(), nullable=False, comment='Содержание'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Идентификатор задачи'),
    sa.Column('file_path', sa.String(), nullable=False, comment='Путь к файлу'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('comments')
    op.drop_table('tasks')
    op.drop_table('activitylog')
    op.drop_table('users')
    op.drop_table('taskstatus')
    op.drop_table('roles')
    op.drop_table('projects')
    # ### end Alembic commands ###
