"""empty message

Revision ID: 0008.project_status_list
Revises: 0007.taskstatus_str
Create Date: 2025-01-08 18:50:42.141370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008.project_status_list'
down_revision: Union[str, None] = '0007.taskstatus_str'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('projects', sa.Column('statuses', sa.ARRAY(sa.String()), nullable=False, comment='Статусы задач'))
    # ### end Alembic commands ###
    op.add_column('projects', sa.Column('statuses', sa.ARRAY(sa.String()), nullable=True, comment='Статусы задач'))

    op.execute("UPDATE projects SET statuses = '{Новые задачи, В процессе, Ревью, Завершенные, Просроченные}' WHERE statuses IS NULL")

    op.alter_column('projects', 'statuses', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'statuses')
    # ### end Alembic commands ###
