version: "3.12"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - app